### ISSUE TITLE
Closed ImportError: cannot import name 'soft_unicode' from 'markupsafe' 

### ISSUE THREAD

**Issue by rajc242** [anandj123/composer-templates#1]
When I am trying to generate DAG based on provided steps then I am getting below error.

```logs
Traceback (most recent call last):
  File "/Users/rajppatel/Documents/gcp/composer-templates/generate_dag.py", line 17, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/rajppatel/Library/Python/3.9/lib/python/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/rajppatel/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/rajppatel/Library/Python/3.9/lib/python/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/rajppatel/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/rajppatel/Library/Python/3.9/lib/python/site-packages/markupsafe/__init__.py)
```

Seems like Jinja and markupsafe has version compatibility issue. I had markupsafe 2.1.1

I resolved an error by downgrading markupsafe with below change.
```shell
pip3 install markupsafe==2.0.1
```

Either we might update requirements.txt file with locking markupsafe version or needs to validate both version.

**Comment by anandj123** [comment]
I fixed the requirements.txt file. Could you try again and let me know if it works?
